### ISSUE TITLE
In Android 10 MultiClient IME is working fine but in Android 12 I am not able to open the IME in secondary screen. Have you tried this IME in Android 12 ?

### ISSUE THREAD

**Issue by uplsuman** [Superpengun/MultiDisplayInput#3]
Error: MultiClientInputMethodManagerService: non-supported operation. callers=com.android.server.inputmethod.MultiClientInputMethodManagerService.access$200:115 com.android.server.inputmethod.MultiClientInputMethodManagerService$ApiCallbacks.reportPerceptibleAsync:1821 com.android.internal.view.IInputMethodManager$Stub.onTransact:480

**Comment by Superpengun** [comment]
> 
Which api version are you using now?
I need more information of your problem
